### ISSUE TITLE
T480 color banding and battery drain

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#1]
there is banding on screen colors. It is especially evident on the launchpad screen.I think it stems from device-id. And how to fix battery drain in sleep mode. When the laptop in sleep mode battery is running low.

**Comment by xma** [comment]
I would be glad to accept your pull request, if you manage to fix something

**Comment by bugraduz** [comment]
if we use:
AAPL,ig-platform-id 00001619 
device-id 16190000 
lilucpu=8

the color banding problem is solved.
I haven't any idea for battery drain on sleep mode.

**Comment by xma** [comment]
All I got was a reboot at clover:
  <key>Boot</key>
   <dict>
     <key>Arguments</key>
     .... lilucpu=8</string>

       <key>PciRoot(0x0)/Pci(0x2,0x0)</key>
       <dict>
         <key>AAPL,ig-platform-id</key>
         <data>AAAWGQ==</data>
         <key>device-id</key>
         <data>FhkAAA==</data>

would you mind sharing your config.plist ?
Do we have to remove WhateverGreen ? Or replace it with a FakePCI_ ? (i.e no WEG at all)

**Comment by bugraduz** [comment]
https://github.com/bugraduz/T480config-hackintosh

**Comment by xma** [comment]
I've tested your config and clover crash :-(

**Comment by bugraduz** [comment]
github.com/bugraduz/T480HackintoshConfig
I updated config. You should try it.

**Comment by xma** [comment]
still crash here :-(

**Comment by xma** [comment]
I've tried inserting a modified EDID in Clover / AAPL00,override-no-connect 
Still the same :-(

**Comment by xma** [comment]
Could you check my last commit
Overthere it's fixed !
![24bpp](https://user-images.githubusercontent.com/548909/79327279-7c515580-7f14-11ea-96ca-9d6552dfe3bd.png)
![launchpad](https://user-images.githubusercontent.com/548909/79327299-82dfcd00-7f14-11ea-835a-338b492f8065.png)

**Comment by xma** [comment]
no reply, plus it's fixed on my machine. closing the issue
