### ISSUE TITLE
Lid close sleep 

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#10]
Lid close sleep can't work. Can you check it?

**Comment by xma** [comment]
it's working fine for me. led blink and laptop goes sleeping

**Comment by xma** [comment]
**pmset -g log | grep -i "wake from"**

```
2020-05-27 19:00:40 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to PWRB/Lid Open Using BATT (Charge:100%) 1816 secs
2020-05-27 21:37:44 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to PWRB/Lid Open Using BATT (Charge:98%) 692 secs
2020-05-27 22:14:22 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to PWRB/UserActivity Assertion Using AC (Charge:95%) 3260 secs
2020-05-28 10:45:01 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to PWRB/Lid Open Using AC (Charge:100%)
2020-05-28 17:44:38 +0200 Wake                	Wake from Normal Sleep [CDNVA] : due to PWRB/Lid Open Using BATT (Charge:84%)

```

**Comment by xma** [comment]
Here are the settings i'm using

**pmset -g**

```
System-wide power settings:
Currently in use:
 lidwake              1
 autopoweroff         0
 standbydelayhigh     86400
 autopoweroffdelay    28800
 standbydelaylow      10800
 standby              0
 proximitywake        0
 ttyskeepawake        1
 hibernatemode        0
 powernap             0
 gpuswitch            2
 hibernatefile        /dev/null
 highstandbythreshold 50
 womp                 0
 displaysleep         180
 networkoversleep     0
 sleep                180
 tcpkeepalive         1
 halfdim              1
 disksleep            10

```

**Comment by bugraduz** [comment]
ı use same peseta settings but my laptop can't wake from sleep. it is when it waking.

**Comment by bugraduz** [comment]
ı use Catalina 10.15.5

**Comment by xma** [comment]
oh you upgraded from Mojave

to change:
** sudo pmset -a hibernatefile /dev/null **

**Comment by bugraduz** [comment]
yes ı updated from Mojave

**Comment by bugraduz** [comment]
ı try sudo pmset -a hibernatefile /dev/null method but 
the problem still has not improved. the laptop does not wake up from sleep, it freezes.

**Comment by xma** [comment]
is there some files in /Library/Logs/DiagnosticReports ? 

verify this is set: hibernatemode        0

do you have any device that are plugged in ? like thunderbolt / display / usb ? 
could you try with nothing plugged ?

if that still doesn't work, could you try without wireless network card ?

**Comment by bugraduz** [comment]
![Ekran Resmi 2020-05-28 23 45 54](https://user-images.githubusercontent.com/39997863/83191958-81bdd480-a13d-11ea-9f1d-2f2612a62f03.png)
[shutdown_stall_2020-05-28-232056_Bugra-MacBook-Pro.shutdownStall.zip](https://github.com/xma/T480-Clover/files/4698158/shutdown_stall_2020-05-28-232056_Bugra-MacBook-Pro.shutdownStall.zip)
![Ekran Resmi 2020-05-28 23 45 08](https://user-images.githubusercontent.com/39997863/83191969-85e9f200-a13d-11ea-917c-9ae6a09b2f63.png)

**Comment by xma** [comment]
I've push config.DW1820a.plist => it has a pci id pci14e4,4331 & pci-aspm-default set to 0

**Comment by bugraduz** [comment]
yes my problem is solvedd thankss but why dont you use hibarnatemode 3 ?

**Comment by xma** [comment]
because i'm a security freak, i don't like the idea of RAM memory stored onto disk, at sleep.
bonus point: less SSD usage by writing way less data onto the disk

**Comment by bugraduz** [comment]
![Ekran Resmi 2020-05-29 00 24 29](https://user-images.githubusercontent.com/39997863/83195377-cdbf4800-a142-11ea-9a98-03f81d4d001d.png)

**Comment by xma** [comment]
ASPM says disabled & path is 0x1C,6. all fine !

**Comment by bugraduz** [comment]
thank you bro

**Comment by xma** [comment]
You're welcome !
