### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#11]
I think you should leave clover and start working on opencore :))) clover is getting old now

**Comment by xma** [comment]
Clover is perfectly fine and feat my needs.

And well, time flow and tools change. 
Before Clover I was using Chameleon.
I've tested VirtualSMC when it was in its infancy (2018). OC is made from same authors.

Only issue would be end of support for EFI driver related to AptioMemoryFix.
Those BIOS powers most of laptop, and require hacks to work.
Fortunately someone extracted it from OC https://github.com/ReddestDream/OcQuirks
That's what I'm using here.

So no point for OpenCore here for now.
