### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#12]
What is the bluetooth firmware version My version is v7 c4689. I saw same forums bluetooth version is v14. 
![Ekran Resmi 2020-05-30 21 00 44](https://user-images.githubusercontent.com/39997863/83335919-b6a26680-a2b8-11ea-87fd-86337ffd2d1f.png)

**Comment by xma** [comment]
![bt](https://user-images.githubusercontent.com/548909/83337387-2ade0980-a2bb-11ea-9930-83c2f68349ad.png)
mine says v14

Perhaps it's different for a DW1820A ?

**Comment by bugraduz** [comment]
No it needs to be updated. but how?

**Comment by xma** [comment]
Ok so i've checked
to know what's the firmware that would load for you card you'd have to look "Vendor ID" & "Product ID"

here for me it's 0489 and E07A

then browse within acidanthera repo

https://github.com/acidanthera/BrcmPatchRAM/tree/master/firmwares/0489_e07a

filename for me is BCM20702A1_001.002.014.1483.1651_v5747.zhx

* it's revision 5747 (end of filename)
* version is 014 (middle)

so for you that would be https://github.com/acidanthera/BrcmPatchRAM/tree/master/firmwares/0a5c_6412

here you can see 
BCM4350C5_003.006.007.0222.4689_v4689.zhx

* revision 4689
* version 007

It's exactly what's displayed on bluetooth info, everything is fine for you.

What we learned here
* there's a bunch of broadcom variants with vendorID/productID , and each one has a specific firmware file
* naming scheme is "version and revision", not just one thing

Based on the list here https://github.com/acidanthera/BrcmPatchRAM

mine is `[0489:e07a] Lenovo China 4352+20702 NGFF`
yours `[0a5c:6412] Dell 4350C5`

**Comment by xma** [comment]
According to this commit https://github.com/acidanthera/BrcmPatchRAM/commit/aeef2b3ffddabbd5856bcdc5c704a7d4b94bddac

That's indeed what's intended for the latest BrcmPatchRAM 2.5.3

- Fixed parsing firmware versions (e.g. 8785 is 4689)
- **Use 4689 firmware for DW1820A [0a5c:6412]**

**Comment by bugraduz** [comment]
You are best hackintosher for me :) thank you. by the way what does it do brcmfixdrv=1 boot arg ?

**Comment by xma** [comment]
you mean brcmfx-driver=1 ?

**Comment by bugraduz** [comment]
yes

**Comment by xma** [comment]
Well if broadcom bluetooth ain't complicated enought, let's talk about apple wifi drivers here :)

Apple right now has two drivers within macOS 10.15

/System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/AirPortBrcm4360.kext
/System/Library/Extensions/IO80211Family.kext/Contents/PlugIns/AirPortBrcmNIC.kext

Depending on which pci vendor/product ID, one is loaded or another.
It's defined by something called "IOProbeScore" within a plist, that says "hey load this one for this specific pci vendor/product"

Here it's even trickier, those drivers are really close, and for some pci vendor/productID : **one or the other could be loaded (and work)**

Here it's https://github.com/acidanthera/AirportBrcmFixup

brcmfx-driver=0|1|2|3 enables only one kext for loading, 0 - AirPortBrcmNIC-MFG, 1 - AirPortBrcm4360, 2 - AirPortBrcmNIC, 3 - AirPortBrcm4331

So by telling 1 we'd force macOS to use internally AirPortBrcm4360

I don't remember exactly every tests I've made but I'd recall one other value worked ( perhaps 0 or 2 ).

**Comment by bugraduz** [comment]
is it neccesary for mine wifi card dw1820a?

**Comment by xma** [comment]
if wifi wasn't working on you machine, I'd think that would be something to have a look, yeah

**Comment by bugraduz** [comment]
my laptop freezes 2-3 times a day and I have to press the power button to turn it off. How can I find out the cause of this problem?

**Comment by xma** [comment]
sorry to hear that

Do you got any report message-box at next login, where it displays a stack-trace / debug info ?
![crash](https://user-images.githubusercontent.com/548909/83357074-7bf90680-a36a-11ea-8142-a3b8f38e57aa.png)

if not, perhaps you could add this to kernel boot-args
`-v keepsyms=1 debug=0x100`

is there any file in /Library/Logs/CrashReporter /Library/Logs/DiagnosticReports ?
