### ISSUE TITLE
ac 8265 Wi-Fi can work now

### ISSUE THREAD

**Issue by kai2ou** [xma/T480-Clover#14]
https://github.com/zxystd/itlwm

**Comment by xma** [comment]
Yeah I know, it has been few months old

Last time I've checked:
* no integration with builtin macOS (i.e you can't select network and enter credential with regular icon)
* only unencrypted or WEP support : and you manualy have to edit a plist with your SSID and passphrase

I'm letting this issue open : it could be handy for some, who don't wan to pay big price over broadcom 2nd hand stuff

**Comment by kai2ou** [comment]
Intel WiFi Client for itlwm [https://github.com/zxystd/HeliPort](https://github.com/zxystd/HeliPort)
Developers are addressing these issues and making great progress.

**Comment by xma** [comment]
Oh great, glad to hear that.

Feel free to post a screenshot or anything to would appeal to :)

**Comment by xma** [comment]
Sadly it doesn't work yet with clover
I've tested with another old lenovo laptop, with OpenCore. it works great!

https://github.com/OpenIntelWireless/itlwm/releases

limitations: no 802.11ac, only 802.11n (still in 5Ghz)
latest alpha 1.3 bring a good speedup (40Mhz instead of 20) : 200mb or so here

**Comment by kai2ou** [comment]
Switch to OpenCore[https://github.com/EETagent/T480-OpenCore-Hackintosh](url)

**Comment by xma** [comment]
haha yeah. It's tempting.

last tme I've reported a bug to clover author 
https://github.com/CloverHackyColor/CloverBootloader/issues/380
he wasn't really helpful at first, to say the least

other laptop where I tested itlwm 1.3 (beta w/ 40mhz) is a Lenovo x260 with clover 0.6.8 : latest stable. Everything was smooth

**Comment by xma** [comment]
closing. not an issue. 
if anyone has interest and provide a pull request, it'll be happily merged
