### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#15]
my panic report 

panic(cpu 0 caller 0xffffff802004aa3a): Kernel trap at 0xffffff802002cf45, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0x000000010d322ccf, CR3: 0x00000001f14db002, CR4: 0x00000000003626e0
RAX: 0xffffff803e646740, RBX: 0x0002000000000000, RCX: 0xffffff803e646740, RDX: 0x00000000065c1740
RSP: 0xffffff9228d73550, RBP: 0xffffff9228d735f0, RSI: 0x0000000000000000, RDI: 0x000000000032e0ba
R8:  0x0000000000000029, R9:  0xffffff8040f08ee0, R10: 0xffffff80347e4438, R11: 0xffffff80347e4400
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0x000000000032e0ba, R15: 0x0000000000000001
RFL: 0x0000000000010246, RIP: 0xffffff802002cf45, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000010d322ccf, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 1, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff801fd51220 : 0xffffff801ff1f5cd 
0xffffff801fd51270 : 0xffffff8020058b05 
0xffffff801fd512b0 : 0xffffff802004a68e 
0xffffff801fd51300 : 0xffffff801fec5a40 
0xffffff801fd51320 : 0xffffff801ff1ec97 
0xffffff801fd51420 : 0xffffff801ff1f087 
0xffffff801fd51470 : 0xffffff80206c27cc 
0xffffff801fd514e0 : 0xffffff802004aa3a 
0xffffff801fd51660 : 0xffffff802004a738 
0xffffff801fd516b0 : 0xffffff801fec5a40 
0xffffff801fd516d0 : 0xffffff802002cf45 
0xffffff9228d735f0 : 0xffffff801ffa5208 
0xffffff9228d73630 : 0xffffff801ffa60c1 
0xffffff9228d739f0 : 0xffffff801ffa53d7 
0xffffff9228d73a50 : 0xffffff80204b9406 
0xffffff9228d73a80 : 0xffffff80201788b5 
0xffffff9228d73b00 : 0xffffff802017815f 
0xffffff9228d73b60 : 0xffffff802017d1c5 
0xffffff9228d73be0 : 0xffffff8020188c96 
0xffffff9228d73c80 : 0xffffff802017e3b3 
0xffffff9228d73cb0 : 0xffffff802017762c 
0xffffff9228d73d20 : 0xffffff802017e00a 
0xffffff9228d73d40 : 0xffffff802048279c 
0xffffff9228d73e00 : 0xffffff802049c7a9 
0xffffff9228d73f40 : 0xffffff8020587097 
0xffffff9228d73fa0 : 0xffffff801fec6206 

BSD process name corresponding to current thread: launchd
Boot args: lilucpu=8 dart=0 bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 brcmfx-country=#a -hbfx-dump-nvram brcmfx-driver=1 

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000001fc00000
Kernel text base: 0xffffff801fe00000
__HIB  text base: 0xffffff801fd00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: YES
Panic diags file available: NO (0xe00002cd)

System uptime in nanoseconds: 36282703421859
last loaded kext at 27307769376320: >!UAudio	323.1 (addr 0xffffff7fa3c36000, size 434176)
last unloaded kext at 27441661784275: >usb.cdc	5.0.0 (addr 0xffffff7fa3c10000, size 28672)
loaded kexts:
me.kishorprins.VoodooInput	1.0.6
as.acidanthera.BrcmPatchRAM3	2.5.3
as.acidanthera.voodoo.driver.PS2Trackpad	2.1.5
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.5
as.acidanthera.mieze.!IMausi	1.0.3
org.hwsensors.driver.ACPISensors	1800
as.acidanthera.voodoo.driver.PS2!C	2.1.5
org.rehabman.driver.!ASmartBatteryManager	1.90.1
org.hwsensors.driver.CPUSensors	1800
as.acidanthera.BrcmFirmwareStore	2.5.3
as.lvs1974.HibernationFixup	1.3.3
as.lvs1974.AirportBrcmFixup	2.0.7
as.vit9696.!AALC	1.5.0
org.tw.CodecCommander	2.7.1
org.acidanthera.NVMeFix	1.0.2
as.vit9696.WhateverGreen	1.4.0
org.vanilla.driver.CPUFriend	1.2.0
as.vit9696.Lilu	1.4.5
org.netkas.driver.FakeSMC	1800
@filesystems.smbfs	3.4.3
@fileutil	20.036.15
>AudioAUUC	1.70
@filesystems.autofs	3.0
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
>!AUpstreamUserClient	3.6.8
>!AHDA	283.15
>!AGraphicsDevicePolicy	5.2.4
@AGDCPluginDisplayMetrics	5.2.4
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.5f6
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IPCHPMC	2.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>!A!ISKLGraphics	14.0.6
>!A!ISKLGraphicsFramebuffer	14.0.6
>!ABacklight	180.3
>!ALPC	3.1
>!ASMCLMU	212
>!AMCCSControl	1.14
>!ATopCaseHIDEventDriver	3430.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@filesystems.apfs	1412.120.2
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>AirPort.Brcm4360	1400.1.1
@private.KextAudit	1.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AGraphicsControl	5.2.4
|IOAVB!F	850.1
>!ASSE	1.0
@!AGPUWrangler	5.2.4
|IOSlowAdaptiveClocking!F	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
>X86PlatformPlugin	1.0.0
|IOAccelerator!F2	438.5.4
@!AGraphicsDeviceControl	5.2.4
>!ABacklightExpert	1.1.0
|IONDRVSupport	576.1
>IOPlatformPlugin!F	6.0.0d8
>!ASMBus!C	1.0.18d1
|IOGraphics!F	576.1
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.5f6
>!AActuatorDriver	3440.1
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	7.0.5f6
|IO!BHost!CUSBTransport	7.0.5f6
|IO!BHost!CTransport	7.0.5f6
|IO!B!F	7.0.5f6
|IO!BPacketLogger	7.0.5f6
>!UMergeNub	900.4.2
|IOSerial!F	11
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IONVMe!F	2.1.0
|IOSkywalk!F	1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.121.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by xma** [comment]
trace doesn't bring anything useful
you should have "-v keepsyms=1 debug=0x100"
