### ISSUE TITLE
Freezing isssu

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#16]
Heyyy last version has problem. My laptop always freezing and restarting. I am sure problem for last version efı. Can you check?

**Comment by bugraduz** [comment]
![P_20200607_000630](https://user-images.githubusercontent.com/39997863/83954564-f508ca00-a852-11ea-9182-fd448fea2852.jpg)

**Comment by xma** [comment]
here it's working nicely

**Comment by xma** [comment]
last version you mean the last commit with nvmefix ?
perhaps try an older one from https://github.com/acidanthera/NVMeFix/releases
I'd suggest you test 1.0.1 which was different - they added some energy stuff that perhaps doesn't play well with your NVME -

**Comment by xma** [comment]
or you simply remove NVMEFix and verify that's what cause problem for your setup

**Comment by bugraduz** [comment]
I m testng now

**Comment by bugraduz** [comment]
No i tested without nvmefix kext problem cant solved

**Comment by xma** [comment]
ok so If you want to go to an older commit

if you're not familiar with git

go there you'll see the list
https://github.com/xma/T480-Clover/commits/master
click on one, let say it's https://github.com/xma/T480-Clover/commit/c4fe00167dfab130973fefc156e838818298334c

note the commit id: last part of url

to get matching commit:
* first you clone repo : `git clone https://github.com/xma/T480-Clover`
* go to directory: `cd T480-Clover`
* switch to matching commit id: `git checkout c4fe00167dfab130973fefc156e838818298334c`

now the folder match this version

if you'd like to go to the current: `git checkout master`

**Comment by bugraduz** [comment]
My laptops memory gives quick random pattern test failed error on diognostic screen :((((((
![IMG-20200607-WA0018_1](https://user-images.githubusercontent.com/39997863/83965812-fa9bf980-a8be-11ea-85ef-0290e9378575.jpg)

**Comment by bugraduz** [comment]
the problem is not caused by CLOVER folder ı m sorry

**Comment by xma** [comment]
_the problem is not caused by CLOVER folder ı m sorry_

it's not a big deal, don't worry

before opening the laptop, don't forget in bios to "Disable Built-In Battery" first.
If you got two memory sticks : try to remove one - perhaps only one is defective

**Comment by bugraduz** [comment]
No ı have one slot memory 16 Gb samsung
