### ISSUE TITLE
HDMI Monitor no signal detected automatically 

### ISSUE THREAD

**Issue by opatotto** [xma/T480-Clover#17]
I used to have Mojave Hackintosh, working with an external monitor, using the direct HDMI connection to my t480, when the computer boot at login automatically detected my monitor and after wake from sleep the signal was detected, I updated the OS using this repo and everything is working fine (actually this is amazing, thanks for sharing) the only thing is at login and after wake from sleep, the signal is not detected automatically, I need to press the power button every time to detect my monitor. 

Where could I look to try to fix this minor issue?

**Comment by xma** [comment]
It's definitely an issue with Whatevergreen

Perhaps this option might have a positive effect:
igfxonln=1

**Comment by xma** [comment]
it works for me : tell me if it's ok for you

**Comment by opatotto** [comment]
Yes its working :)

**Comment by xma** [comment]
would you mind if i add a line in README.md with your handle that says HDMI works fine at boot/wake,
next to "No color banding, Display is correctly seen as 24-Bit Color (ARGB8888) : issue reported by @bugraduz"

That's the hall of fame of bug reporter here :)

**Comment by opatotto** [comment]
It's Ok, thanks for that :)

**Comment by xma** [comment]
Yeah, we shouldn't be shy at it's the first and perhaps only github repo. for a T480 hackintosh with those features ! :)
