### ISSUE TITLE
slow boot 

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#2]
Catalina booting very slowly. is your laptop has same problem? Especially when open the desktop first time, the laptop freezes for 2-3 minute.the computer reacts late.

**Comment by xma** [comment]
For me it's fine, way less than 1 minute for all of those:
- Clover
- Filevault2 passphrase input
- macOs starting

Did you tried OpenCore for having a baseline comparison ?
This one works : https://github.com/taina0407/T480-OpenCore-Hackintosh 

for working wifi :  I've renamed config-wifi-DW1820A.plist to config.plist
it was OK even if my card is a DW1560

**Comment by xma** [comment]
Cold boot, from button to working macOs : 1min02sec

including BIOS (password) / Clover / FV2 (password) & macOS

**Comment by bugraduz** [comment]
Does your computer have SSD trim support? Does 'trım support = yes' appear in the system report?

**Comment by xma** [comment]
Yes
![status](https://user-images.githubusercontent.com/548909/79037103-90245100-7bce-11ea-9ef1-f729846ac706.png)

**Comment by bugraduz** [comment]
can you update clover r5109

**Comment by xma** [comment]
done

If you want to update by yourself: it's there https://github.com/CloverHackyColor/CloverBootloader/releases
