### ISSUE TITLE
Shutdown problem

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#21]
I am clicking shutdown button but my thinkpad restarting. What is the solution.

**Comment by opatotto** [comment]
If I press the power on/off ThinkPad button it goes to sleep mode without problems

**Comment by bugraduz** [comment]
ı click shutdown button on apple logo but my laptop restarting

**Comment by opatotto** [comment]
It happened to me, after pressing around 2-3 seconds power on/off button went directly to sleep mode without power options window (trying to reproduce your bug), woke up and after clicking power off the bug happened.

But after restarting is working normally. Even if I'm trying to reproduce the bug now it appears the power option window. 

Can you try to reproduce the bug? Do you still have the bug after restarting?

**Comment by sure15** [comment]
The same issue.
