### ISSUE TITLE
The touch panel is not working properly

### ISSUE THREAD

**Issue by bdragonh** [xma/T480-Clover#23]
The touch panel is not working properly, indicating that it is searching

**Comment by xma** [comment]
in README.md i've never said my machine was having a touch screen.
so you are on your own, good luck !

**Comment by xma** [comment]
anyway if you happen to make it work, i would gladly accept your pull request

**Comment by bdragonh** [comment]
Solved the problem of touch panel （https://github.com/bdragonh/T480S-EFI <https://github.com/bdragonh/T480S-EFI>） 
thank you
