### ISSUE TITLE
T480 unable to get past Apple Logo

### ISSUE THREAD

**Issue by Swimming33** [xma/T480-Clover#28]
Hi! Sadly having trouble getting this working with my T480 (i7-8650u and MX150), I was wondering if there's any steps I'm forgetting to take or messed up (which is quite possible). I've made a Catalina .7 install usb, installed clover bootloader to it, replaced the Clover folder with the provided one, added the SMBIOS, and then booted the bootloader. I am using the intel wifi card at the moment though, and with -v, it shows that there's a "GV wake-failure". 
Thanks so much for making this project regardless ofc :) !

**Comment by sure15** [comment]
The same with you.I have to recover my computer,and use the old version, this made a big error.
