### ISSUE TITLE
UNKOWN CPU

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#29]
I have unkown cpu problem. ı m using BİG SUR.

**Comment by xma** [comment]
oh weird, here with catalina my commit fixed it
https://github.com/xma/T480-Clover/commit/3207e9f764f39ad18c5810eccfb614072a9dc2e5

could you check if you added <key>CPU</key><dict></dict> within your config.plist ?

I'm gonna upgrade to Big Sur once final version is released (read: it should be really soon!)

cheers

**Comment by xma** [comment]
could you check with latest commit (ie git pull or git clone ) ? because I had forgotten a file drivers/UEFI/OpenRuntime.efi from clover 5126

**Comment by xma** [comment]
![bigsur](https://user-images.githubusercontent.com/548909/98877001-c33e0400-247f-11eb-86d5-8f99e6843fb7.png)

works fine here
