### ISSUE TITLE
SMBIOS

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#32]
Why dont you change SMBIOS model. T480 is use i7 cpu but macbook 14.1 use i5 cpu.

![Ekran Resmi 2020-11-13 22 20 38](https://user-images.githubusercontent.com/39997863/99112286-7af92000-25fe-11eb-9f4a-492b4bb35d1c.png)

Macbook Pro 16.3 is looks very like t480 specs
For example 
macbook 16.3 cpu = i7 8557u
My t480 cpu = i7 8550u 
👍 
:))

**Comment by xma** [comment]
smbios model doesn't matter much
it's superspeed by some handy settings here, in this repo:
* correct cpu frequency / step are took from a valid cpufriend settings => not from smbios
* correct usb port mapping => USBPorts.kext
* working gpu support => whatevergreen does the job
