### ISSUE TITLE
HWmonitor

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#33]
hwmonitor Why does not  show all informations. ex fan rpm or you fren?

**Comment by xma** [comment]
You are right. fan rpm information is now missing. before it was ok with FakeSMC 
now it's VirtualSMC ( for OC and recent clover) which doesn't provide fan rpm.

If you happen to have a solution : feel free to share, I'll gladly integrate it !

**Comment by xma** [comment]
I've added YogaSMC https://github.com/zhen-zen/YogaSMC

YogaSMC can do way more thant just reading fan rpm : 
- battery threshold 
- setting keyboard backlight
- controlling LED
=> There's a prefpane to configure that, in the app dmg https://github.com/zhen-zen/YogaSMC/releases

here on iStat Menus, fan rpm are now visible
![yoga1](https://user-images.githubusercontent.com/548909/101225998-4aebec80-3693-11eb-859b-759783812cdb.png)

**Comment by bugraduz** [comment]
ohh thanks man. it was very successful. Can ı see cpu frequency? because ı am using laptop in battery mode ı save battery power. I want to switch like low power mode.

**Comment by bugraduz** [comment]
SSDT-ECRW.dsl access unavailable? what does it mean? Yoga is not show fan rpm

**Comment by xma** [comment]
the error is for setting fan speed : you can turn it off and bypass system
read was ok (see my screenshot)

anyway I've updated SSDT ACPI  ( from this repo https://github.com/YBN-JUAN/X1C6-OpenCore-EFI )
it has some change on the battery side (now I got temperature for battery in iStat Menus)

now YogaSMCNC can set value for fan rpm  "ECAccess : RW"
![ECAccess_RW](https://user-images.githubusercontent.com/548909/101243419-6d681f00-3700-11eb-92cc-2c7a5e65f5ac.png)

personaly I don't recommend playing with this - just let System manage fan by itself, it's safer.

**Comment by bugraduz** [comment]
wow ı tested it, you are best Hackintosher :))) but I think we should pass opencore. what do you think about opencore thinktosh?

**Comment by xma** [comment]
About you opencore rant, you already asked that in another commit few months ago. do you remember?
Plus now Clover *integrate* OC, so there's nothing to gain. at all.

I'm not satisfied with last commit - battery expected duration isn't displayed anymore in iStat Menus. that's a regression.
it's far more usefull compared to "settings fan speed" imho

**Comment by xma** [comment]
I've modified SSDT - iStat Menus show duration and ECAccess:RW

**Comment by bugraduz** [comment]
Can we increase the gpu power? I feel it is very low compared to windows.

**Comment by xma** [comment]
you should check https://github.com/stevezhengshiqi/one-key-cpufriend
I've choose for something low, but there's a performance settings I'd recall

**Comment by bugraduz** [comment]
I checked, but I could not understand how to change this setting. How to choose 1 2 3 4?

**Comment by xma** [comment]
closing this issue as it's not related anymore to HWMonitor
