### ISSUE TITLE
Headphone problem

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#34]
I have headphone plug problem after wake sleep. Sound is not good. Can you check it? 
my solution is 
sudo kill -9 `ps ax|grep 'coreaudio[a-z]' | awk '{print $1}'`
terminal code after wake sleep.

**Comment by bugraduz** [comment]
this problem also applies to speaker. After wake sleep sound not working correct. İf ı press sound increase button , strange sounds come in speaker.

**Comment by xma** [comment]
oh.
Would you mind testing this repo : https://github.com/EETagent/T480-OpenCore-Hackintosh
If problem is there too - when you wake after sleep or not ?

**Comment by bugraduz** [comment]
this is exactly the same problem and amateur solution
https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/10

**Comment by xma** [comment]
tha's a too long thread. just browsing it quickly didn't inspire me at all.

some said "add codecommander", others said "change layout-id"

the last comment / post telling it's ok 
https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/10#issuecomment-717621682 
=> it points to a kext change related to airport/wifi, which doesn't make sense.

**Comment by bugraduz** [comment]
It was a very interesting solution method. I'm not sure either ...

**Comment by xma** [comment]
lazy way would be to automate your "kill -9 " when computer is waking up

there's a software package "sleepwatcher" that exists (and i'm using it) that could call scripts : on sleep & on wake events.

easiest way to install sleepwatcher:

git clone https://github.com/tluck/Lenovo-T460-Clover/
cd Lenovo-T460-Clover/Utilities/
./install_sleepwatcher.command


then you can edit
/etc/rc.sleep
=> remove everything

/etc/rc.wakeup
=> put your stuff in

**Comment by xma** [comment]
While browsing github, I came across something related
https://github.com/xxxzc/xps15-9550-macos

in README.md

Headphone
After updating to 10.15, headphone will be distorted after a few minutes in battery mode.

You have to install ComboJack (run install.sh).


=> For you, does headphone sounds bad after few minutes in battery mode too ?

'ComboJack' https://github.com/hackintosh-stuff/ComboJack

It might be a path for solving the problem - but it's now 100% perfect, T480 have "alc257" chipset
and ComboJack handle alc256/alc255

chipset are different - but at the same time very close, I'd think it may be possible to add support for alc257 in ComboJack without too much effort.

**Comment by bugraduz** [comment]
yes now ı tested it , sound is  breaking in battery mode after 1-2 minutes

**Comment by xma** [comment]
oh ok. 
Did it came with big sur ? I recall using t480 like watching movies w/ headphone earlier this year and it was ok.

Right now I've put headphones and tried to listen spotify / youtube. it's HORRIBLE I confess :=(

**Comment by xma** [comment]
I've added 'VerbStub.kext' in this repo ( kexts/Other/VerbStub.kext )
by itself this kext won't do anything good or bad. It's a 'hole' that need to be driven by software.

You gotta have this kext

next step : ComboJack

I've quickly hacked it for alc257 (not yet complete)

https://github.com/xma/ComboJack

cd ComboJack_Installer
sudo ./install.sh

You gotta reboot 

to verify is well here:

$ kextstat | grep -i verb
   59    0 0                  0xf000     0xf000     com.XPS.VerbStub (1.0.3) 41D18E8C-8EFF-34A1-BD9C-2D806283284F <14 5 3>
=> kext is there

$ ioreg -l | grep VerbStub
=> should output lots of line = it's ok. normally it's empty

$ ps aux | grep ComboJack
root              2093   0.0  0.0  4515376   2304   ??  Ss    4:10PM   0:00.02 /usr/local/sbin/ComboJack
=> software is there 

If you plug headphone there's a popup 
![popup](https://user-images.githubusercontent.com/548909/102015903-78552c00-3d5e-11eb-81b8-dc1a135a2d66.png)

Tell me if it works for you - right now for me it's fairly good

**Comment by bugraduz** [comment]
Problem is solved. Thanks for @xma 👍

**Comment by xma** [comment]
ah great 👍 
I'll update README.md soon
