### ISSUE TITLE
Different cpu

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#35]
My cpu is i7-8550u but your cpu is i7-8250u

**8250U** 
Processor Base Frequency
1.60 GHz
Max Turbo Frequency
3.40 GHz

**8550U**
Processor Base Frequency
1.80 GHz
Max Turbo Frequency
4.00 GHz

How can ı do correct options for my CPU for example Max Turbo Boost Frequency.

**Comment by xma** [comment]
it's explained in README.md ; you have to use one-key-cpufriend https://github.com/stevezhengshiqi/one-key-cpufriend
