### ISSUE TITLE
Memory slots

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#36]
t480 is have two memory slots but write one slots in system report .
![Screen Shot 2020-12-16 at 10 35 02](https://user-images.githubusercontent.com/39997863/102318516-7f608200-3f8a-11eb-88ec-eba76884ebfb.png)

**Comment by xma** [comment]
here it's working.
![memOK](https://user-images.githubusercontent.com/548909/102322024-b6c93180-3f7e-11eb-9aae-d611dd3d37e7.png)

Are you sure you're using config.plist from this repo ?

**Comment by bugraduz** [comment]
yes ı am sure but ı have one channel 16 gb ram. but it should still show the other slot as empty.

**Comment by xma** [comment]
well then put a 16GB stick in it and it'll be same as me :=)
