### ISSUE TITLE
Slow Boot tx_flush

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#37]
this problem really started to annoy me now. I photographed them all. My computer boots in 16 minutes. It constantly writes tx_flush on the screen and it progresses very slowly.

![1](https://user-images.githubusercontent.com/39997863/102319166-8045e380-3f8b-11eb-9944-d335f6b6b539.jpg)
![2](https://user-images.githubusercontent.com/39997863/102319188-86d45b00-3f8b-11eb-982f-32a7d39d94e9.jpg)
![3](https://user-images.githubusercontent.com/39997863/102319195-89cf4b80-3f8b-11eb-9a3f-fada977ad9b0.jpg)
![4](https://user-images.githubusercontent.com/39997863/102319204-8d62d280-3f8b-11eb-841a-e0a9df30da38.jpg)

**Comment by xma** [comment]
is it the same as https://github.com/xma/T480-Clover/issues/5 ?

It should be equaly slow with an OpenCore T480 config : you tested it ?

**Comment by bugraduz** [comment]
Yes opencore clover it doesn't matter :((((

**Comment by xma** [comment]
So it ain't specific with my repo.

It still point to the factory lenovo drive then
