### ISSUE TITLE
Can you share

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#38]
Can you share system report nvmexpress and pci info screenshot for me please ?

**Comment by bugraduz** [comment]
![Screen Shot 2020-12-16 at 14 25 17](https://user-images.githubusercontent.com/39997863/102342613-8e572c80-3faa-11eb-83be-a2fa5e4aafab.png)
Mass storage controller ??? 
what does it mean?

**Comment by bugraduz** [comment]
![Screen Shot 2020-12-16 at 11 20 50](https://user-images.githubusercontent.com/39997863/102342666-a038cf80-3faa-11eb-8499-d17a60649007.png)

**Comment by bugraduz** [comment]
your config.plist devices is different for my Hackintool infos
for example
![Screen Shot 2020-12-16 at 14 37 52](https://user-images.githubusercontent.com/39997863/102343986-4b965400-3fac-11eb-8a74-a6ab9a434ccb.png) 
this device is not found in my computer

or
![Screen Shot 2020-12-16 at 14 38 49](https://user-images.githubusercontent.com/39997863/102344100-75e81180-3fac-11eb-93a4-85fe44309c64.png)
your PciRoot(0x0)/Pci(0x1f,0x0) device compatible pci8086,9cc1 
but my PciRoot(0x0)/Pci(0x1f,0x0) device compatible pci8086,9d4e

**Comment by bugraduz** [comment]
THİS THREAD İS İMPORTANT T480 https://github.com/acidanthera/bugtracker/issues/1030

**Comment by xma** [comment]
https://github.com/xma/T480-Clover/issues/5#issuecomment-616797096

same hardware, same nvme drive nothing changed
how bizarre it didn't work anybetter !

lenovo nvme drive ain't working good. I can't do anything about it

**Comment by xma** [comment]
![nvme](https://user-images.githubusercontent.com/548909/102402664-6b963980-3fe5-11eb-9fa3-6712870022e9.png)

https://www.samsung.com/us/computing/memory-storage/solid-state-drives/ssd-970-evo-nvme-m-2-1tb-mz-v7e1t0bw/

**Comment by xma** [comment]
![Uploading pcie.png…]()

**Comment by bugraduz** [comment]
I solved my problem by replacing my ssd disk. My new ssd drive is called "Sandisk Ultra 3D NVME 500GB". Lenovo SSD is really bad for macOS.

**Comment by xma** [comment]
great 👍
