### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#45]
battery status shows wrong when not charging

**Comment by xma** [comment]
no screenshot, no explanation. lovely "bug" report
![system_report](https://user-images.githubusercontent.com/548909/136269651-f9d2f7e5-e12a-4e11-8dcf-47ad68639dcc.png)

here it shows correct percentage in battery indicator, right corner next to clock
system report shows correct information too

**Comment by xma** [comment]
no further information
