### ISSUE TITLE
APFS Slow

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#5]
There was no such problem when using the mojave operating system(HFS+). But with the installation of the catalina operating system(APFS), this problem occurred. Especially the boot time is too long and the desktop and dock freezes for 10 seconds when the computer is turned on, the computer doesnot react for a few minutes. The dock hangs when turning off the computer, the desktop freezes. I tried sudo trim force enable/disable , clover TRIM patch enable/disable.
What do you think about this problem?

**Comment by xma** [comment]
Hello,

Hard to tell, I've never seen a slow boot myself on a hackintosh
I've always enabled hex patch for enabling TRIM patch onto Clover.

Did you looked onto log from the machine ? Perhaps there's an hidden issue somewhere
do it after a fresh boot, to minimize input :

log show --last boot --style compact > /tmp/log

On my machine I've removed a lot of useless apple stuff - perhaps it could speed up for you?
https://gist.github.com/pwnsdx/1217727ca57de2dd2a372afdd7a0fc21

You'd have to follow this for applying it:
* logout of apple : System Preferences-> Apple ID > Sign Out
* reboot and choose Recovery at Clover
* select disk utility in top menu, choose your drive and the icon on the right "Mount"
* exit disk utility and choose terminal in top menu
* go to the root of you volume (ex: cd /Volumes/Macintosh\ HD )
* launch the script with full path (ex: sh /Volumes/Macintosh\ HD/Users/sabri/Desktop/disable.sh )

Only minor issue for me : calendar app was then broken
on recovery I've fixed it this way

cd System/Library/LaunchAgents
mv com.apple.CalendarAgent.plist.bak com.apple.CalendarAgent.plist

**Comment by bugraduz** [comment]
SSDT-NVME.aml what is this file about? I have different oem ssd. My ssd is Lenovo LENSE30256GMSP34MEAT3TA. I think need different patch for ssd.

**Comment by xma** [comment]
I've disassembled SSD-NVME.aml and looked it:

- It's related to power management, it adds a node "deep-idle" probably to enhance battery life

- It's for RP09 whereas on my computer NVME disk is plugged as RP11 ( seen in IOJones )
it means it's totaly useless here (and doesn't do any harm)

source code here: https://github.com/kk1987/T480s-hackintosh/blob/a2334682e1775d6e28a7dabce96d45ca34fa3464/ACPI/dsl/SSDT-NVME.dsl

=> Right now it's NVMeFix kext that handle NVME thing

**Comment by xma** [comment]
power management info:

smartctl -a /dev/nvme0
Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     6.20W       -        -    0  0  0  0        0       0
 1 +     4.30W       -        -    1  1  1  1        0       0
 2 +     2.10W       -        -    2  2  2  2        0       0
 3 -   0.0400W       -        -    3  3  3  3      210    1200
 4 -   0.0050W       -        -    4  4  4  4     2000    8000

**Comment by xma** [comment]
Look like other people have issue with this drive, unfortunately. And not even with macOS

https://www.reddit.com/r/thinkpad/comments/btj4i1/anyone_else_have_a_lense30256gmsp34meat3ta_i/

**Comment by bugraduz** [comment]
I am not having any problems in NTFS or HFS + file system. I'm having this problem only if my disk is in APFS format. I have tested the SSD is running east.

**Comment by xma** [comment]
Did you tried without NVMeFix ? it's unlikely to solve anything but i'm curious

**Comment by bugraduz** [comment]
yes I tried nvmefix.kext. I ınstalled the kext C/K/O. Do I need to take any other action about the kext?

**Comment by xma** [comment]
I'm no expert but I would try a DEBUG build, and check the log output

**Comment by xma** [comment]
https://github.com/acidanthera/bugtracker/issues

**Comment by bugraduz** [comment]
where can i find recorded log files?

**Comment by xma** [comment]
log show --last boot | grep -i "nvme" perhaps

**Comment by bugraduz** [comment]
2020-04-21 11:23:00.632997+0300 0x73       Default     0x0                  0      0    kernel: (kernel) NVMeFix      init: @ (DBG) NVMeFix bootstrap DBG-102-2020-04-06
2020-04-21 11:23:00.633008+0300 0x73       Default     0x0                  0      0    kernel: (kernel) NVMeFix     nvmef: @ (DBG) Registered for matching notifications

**Comment by xma** [comment]
Hmm, that's not much

check if power management is enable :

ioreg -l IONVMEController | grep -i apst

here "apst" = Yes

**Comment by xma** [comment]
Oh and there's a boot args to add onto clover for verbose nvmefix
-nvmefdbg

**Comment by bugraduz** [comment]
APST=YES ok. I. am i already added the argument -nvmefdbg. but the log result is the same.
