### ISSUE TITLE
EC control

### ISSUE THREAD

**Issue by pierpaolodimarzo** [xma/T480-Clover#53]
Hi bro, 
I tried your EFI, and it works very well, I wanted to ask you if it was possible to have the EC patch, separately from the SSDT battery.
I read that you moved RE1B / RECB / WE1B / WECB from SSDT-EC to SSDT-BATT; 

Is it possible to have the SSDT-EC file?
Thanks a lot!

**Comment by xma** [comment]
Hello,
I didn't undestood what you want/mean there, 
and the usefulness of having one more file.

regards

**Comment by pierpaolodimarzo** [comment]
Hi,
I mean if you have the SSDT-ECRW file for the T480
thanks

**Comment by pierpaolodimarzo** [comment]
solved the problem, thanks!
