### ISSUE TITLE
HDMI output sound problem

### ISSUE THREAD

**Issue by linsuaw** [xma/T480-Clover#7]
Thank you for sharing, most of them are working properly
Currently encountered HDMI output TV, but the sound is still laptop output
The red dot moves slowly
Any suggestions?

**Comment by xma** [comment]
I've tested hdmi here - last commit is ok
could you star this repository :)

**Comment by xma** [comment]
_The red dot moves slowly_

I've made a commit https://github.com/xma/T480-Clover/commit/84a796939ff54b86e111fe65dfa2aa5cc79cabd3
It should fix the speed issue - I didn't noticed it because I'm not using Trackpoint at all

**Comment by xma** [comment]
If you'd like to modify speed it's MouseMultiplierX and MouseMultiplierY
you've to compile dsl file with iasl afterward

**Comment by linsuaw** [comment]
I update it , and it work perfect！thanks a lot!
