### ISSUE TITLE
What's the battery consumption?

### ISSUE THREAD

**Issue by sure15** [xma/T480-Clover#8]
How long can this laptop work in MacOS?
Does the dGPU still consume battery in MacOS?
Does this laptop work longer under windows than under MacOS？
Thanks for your reply.

**Comment by xma** [comment]
>Does the dGPU still consume battery in MacOS?
dGPU is turned off in DSDT/SSDT
the device is turned off, no PCI device at all : for example lspci under linux (with clover boot and patches) doesn't show nvidia device
I'd assume there isn't much more todo here

>Does this laptop work longer under windows than under MacOS？
My laptop originally has windows 10 but I didn't used it at all and installed macOS straight away, so I can't tell.

>How long can this laptop work in MacOS?
Short question, long answer : it depends

* Hardware level , laptop aren't equal
More RAM you get, more Watt consumption would ensue ( ie: 8G vs 32G  )
Different SSD/NVME brands and models/size : each has a different power requirement
Battery : I've replaced the external one with 61++ 72Wh, it's heavier but it brings longer usage

* Usage
** Brightness level : darkening the screen would reduce power usage
** Apps: Chrome is known to be more power hungry compared to safari
and even, a website could have a bad javascript that eat power in the background

**Comment by xma** [comment]
Intel has made a tool for measuring power: https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html
![power1](https://user-images.githubusercontent.com/548909/82368001-f6459480-9a14-11ea-8f65-1ad115180aa2.png)

**Comment by xma** [comment]
Overall with 72Wh battery , idle:
macOS estimate running time (idle) : 14 hours
power drain is about 7W

you could get those with iStat Menus : https://bjango.com/mac/istatmenus/

**Comment by sure15** [comment]
Thanks for your reply.
By [this link](https://www.notebookcheck.net/Lenovo-ThinkPad-T480-i7-8550U-MX150-FHD-Laptop-Review.293682.0.html) from NBC, we could know the Power Consumption and Battery Runtime under Windows.
<img width="509" alt="截屏2020-05-20 18 52 25" src="https://user-images.githubusercontent.com/8850574/82438329-72021880-9acb-11ea-851c-dfae72bce469.png">
<img width="726" alt="截屏2020-05-20 18 52 50" src="https://user-images.githubusercontent.com/8850574/82438338-77f7f980-9acb-11ea-915c-eec8d6197732.png">
It seems that the power drain of the laptop of NBC is 7W, the same as your Hackintosh.
But the running time (idle) is 27 hours with a 72Wh battery, much longer than yours.
So what's the differences between the two laptop?

**Comment by xma** [comment]
I'm closing this issue

feel free to do a pull request or reopen this issue if you've anything to enhance battery time on macOs
