### ISSUE TITLE
HDMI sound

### ISSUE THREAD

**Issue by bugraduz** [xma/T480-Clover#9]
can you check HDMI sound,
please rebuild Framebuffer patch

**Comment by xma** [comment]
Hi
Here it's finally fixed, could you test it ?

**Comment by xma** [comment]
it might broke DP output. but i don't have DP / USB-C display nor adapter to test

**Comment by xma** [comment]
It's a duplicate https://github.com/xma/T480-Clover/issues/7
original reporter said it fixed for him so I'd assume it's ok here. closing.
